export enum CourseErrorCode {
  INSTRUCTOR_NOT_FOUND = "INSTRUCTOR_NOT_FOUND",
  MISSING_OR_INVALID_PARAMETERS = "MISSING_OR_INVALID_PARAMETERS",
  COURSE_NOT_FOUND = "COURSE_NOT_FOUND",
  INVALID_COURSE_ID = "INVALID_COURSE_ID",
}
